### ISSUE TITLE
Import - k čemu slouží sloupec Kuchyň

### ISSUE THREAD

**Issue by mareksip** [mareksip/lilka-pokladna-eet#2]
Vysvětlit návaznosti vlastnosti Kuchyň při importu (tiskne se na objednávky) + vytvořit návod jak se tiskne objednávka do kuchyně.

**Comment by ghost** [comment]
Zde je návod pro tisk do kuchyně: https://lilka.arrowsys.cz/printerkitchen.html
Příliš jsem nepochopil první část úkolu, mohu poprosit o podrobnější vysvětlení?

**Comment by mareksip** [comment]
Už jsme Kuchyň v importu popsali, díky.
